# https://book.getfoundry.sh/reference/config/overview
# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

ignored_warnings_from = [
    "lib/ens-contracts/contracts/registry/ENSRegistry.sol",
    "lib/ens-contracts/contracts/ethregistrar/BaseRegistrarImplementation.sol",
    "lib/ens-contracts/contracts/wrapper/NameWrapper.sol",
]

[fuzz]
runs = 4096

[lint]
lint_on_build = false
